USE  project;

SELECT *
FROM customer_behavior;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT 
	gender,
    SUM(purchase_amount) AS revenue
FROM customer_behavior
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer_behavior
WHERE discount_applied = 'YES' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT *
FROM (SELECT 
	item_purchased,
    ROUND(AVG(review_rating), 2) AS 'average_review_rating'
FROM customer_behavior
GROUP BY item_purchased
)t
ORDER BY average_review_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amount between Standard and Express Shipping?
SELECT 
	shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more?
	-- Compare average spend and total revenue between subscribers and non-subscribers
SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customers,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
	item_purchased,
    ROUND(100 * SUM(CASE 
		WHEN discount_applied = 'Yes' THEN 1 ELSE 0
	END)/ COUNT(*), 2) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous
-- purchase, and show the count of each segment?
WITH customer_type AS (
	SELECT 
		customer_id,
        previous_purchases,
        CASE 
			WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
		END AS customer_segment
    FROM customer_behavior
)

SELECT 
	customer_segment,
	COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
	SELECT 
		category,
		item_purchased,
		COUNT(customer_id) AS number_of_sold,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
) 
SELECT *
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
	subscription_status,
	COUNT(customer_id) AS repeated_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT 
	age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;



SELECT *
FROM customer_behavior
WHERE subscription_status = 'Yes' AND gender = 'Female'